language: objective-c
xcode_project: PromiseKit.xcodeproj
install:
  - gem install travis-xcodebuild
  - carthage bootstrap
xcode_scheme: [PMKiOS, PMKOSX]
xcode_sdk: [iphonesimulator9.3, macosx10.11]
osx_image: xcode7.3

matrix:
  exclude:
    - xcode_scheme: PMKOSX
      xcode_sdk: iphonesimulator9.3
    - xcode_scheme: PMKiOS
      xcode_sdk: macosx10.11

branches:
  only:
    - master

script: travis-xcodebuild