language: objective-c
osx_image: xcode8

env:
  - iOS= DST='platform=iOS Simulator,name=iPhone 6S' UUID='7FC06F6D-AF72-4B38-9A96-1F934EA2E27F' ACTION=test
  - tvOS= DST='platform=tvOS Simulator,name=Apple TV 1080p' UUID='0DF1B136-A3A7-4C51-AE6E-CFEFDF52DA24' ACTION=test
  - macOS= DST='platform=OS X' ACTION=test
  - watchOS= DST='platform=watchOS Simulator,name=Apple Watch - 38mm' ACTION=build

script:
  - if [ -n "$UUID" ]; then xcrun instruments -w "$UUID" || true; sleep 15; fi
  - set -o pipefail && xcodebuild -scheme PromiseKit -destination "$DST" $ACTION | xcpretty
